// src/routes/(public)/jobs/[id]/+page.svelte
<script lang="ts">
  import { getRemainingTime } from "$lib/helpers/getRemainingTime.ts";
  import { parseString } from "$lib/helpers/parseString.ts";
  import type { PageProps } from "./$types";

  const { data }: PageProps = $props();
  const { job } = data;
</script>

<section class="p-24">
  <div class="border border-gray-200 min-h-screen rounded-lg p-12">
    <h1 class="text-3xl font-black text-gray-900">{job.title}</h1>
    <p class="italic inline-flex gap-2 mt-2 text-gray-400">
      <img src="/vendor/octicons/mention.svg" alt="At Symbol Icon" width="18" />
      {job.organization.name}
    </p>
    <div class="mt-4">
      <span
        class="bg-gray-200 text-gray-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded-full inline-flex gap-2"
      >
        <img src="/vendor/octicons/location.svg" alt="Location Icon" width="16" />
        {job.location}
      </span>
      <span
        class="bg-green-200 text-gray-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded-full inline-flex gap-2"
      >
        <img src="/vendor/tabler/coins.svg" alt="Salary" width="16" />
        <!-- TODO Use user's locale in `toLocaleString()` -->
        {job.salary.toLocaleString("en-US")} {job.currency}/{job.salaryPer}
      </span>
      <span
        class="bg-red-200 text-gray-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded-full inline-flex gap-2"
      >
        <img src="/vendor/octicons/clock.svg" alt="Money Icon" width="16" />
        {getRemainingTime(job.expiresAt)}
      </span>
    </div>
    <hr class="h-px my-8 mb-16 bg-gray-600 border-0 w-[300px]" />
    <h3 class="text-2xl font-bold text-gray-800 mb-4">Description</h3>
    <p>
      {job.description}
    </p>
    <h3 class="text-2xl font-bold text-gray-800 my-4">Requirements</h3>
    <ul class="list-disc ml-8">
      {#each parseString(job.requirements) as requirement}
        {#if requirement}
          <li>{requirement}</li>
        {/if}
      {/each}
    </ul>

    <div class="mt-6">
      <a href={job.applicationUrl} class="btn btn-xl bg-black text-white w-fit rounded-full">Apply</a>
    </div>
  </div>
</section>

// src/app/(public)/jobs/[id]/page.tsx
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { db } from "@/lib/db/db.ts";
import { parseString } from "@/lib/helpers/parseString.ts";
import type { ReactElement } from "react";

type Props = {
  params: {
    id: string;
  };
};

export default async function JobPage({ params }: Props): Promise<ReactElement> {
  const job = await db.query.job.findFirst({
    columns: {
      id: true,
      title: true,
      description: true,
      location: true,
      salary: true,
      salaryPer: true,
      currency: true,
      applicationUrl: true,
      requirements: true,
      createdAt: true,
      updatedAt: true,
    },
    with: {
      employer: {
        columns: {
          slug: true,
          name: true,
        },
      },
    },
    where: (job, { eq }) => eq(job.id, params.id),
    orderBy: (job, { desc }) => [ desc(job.updatedAt) ],
  });

  if (!job) {
    notFound();
  }

  return (
    <div className="w-full max-w-4xl px-9">
      <h1 className="text-3xl font-black text-gray-900 mb-2">{job.title}</h1>
      <Link
        href={`/orgs/${ job.employer.slug }`}
        className="inline-flex items-center gap-2 mb-3 text-lg font-bold text-gray-900 hover:text-gray-700"
      >
        <Image src="/vendor/octicons/organization.svg" alt="Employer" title="Employer" width="18" />
        {job.employer.name}
      </Link>
      <div className="mb-6">
        <span className="inline-flex items-center gap-1.5 mr-2 py-2 px-4 text-sm font-medium text-gray-800 bg-gray-200 rounded-full">
          <Image src="/vendor/octicons/location.svg" alt="" width="16" />
          Work location: {job.location}
        </span>
        <span className="inline-flex items-center gap-1.5 mr-2 py-2 px-4 text-sm font-medium text-gray-800 bg-green-200 rounded-full">
          <Image src="/vendor/tabler/coins.svg" alt="" width="16" />
          {/* TODO Use user's locale in `toLocaleString()` */}
          Salary: {job.salary.toLocaleString("en-US")} {job.currency}/{job.salaryPer}
        </span>
      </div>
      <div className="inline-flex items-center gap-1.5 justify-end w-full mb-6 text-sm">
        <Image src="/vendor/octicons/clock.svg" alt="" width="16" />
        {/* TODO Use user's locale in `toLocaleString()` */}
        Last updated at {(job.updatedAt ?? job.createdAt).toLocaleDateString("en-US")}
      </div>

      <section className="mb-5">
        <h3 className="text-2xl font-bold text-gray-800 mb-2">Description</h3>
        <p>
          {job.description}
        </p>
      </section>

      <section className="mb-5">
        <h3 className="text-2xl font-bold text-gray-800 mb-2">Requirements</h3>
        <ul className="list-disc ml-8">
          {parseString(job.requirements).map((requirement, index) => {
            if (requirement) {
              return <li key={index}>{requirement}</li>;
            }
            return null;
          })}
        </ul>
      </section>

      <section className="mt-8">
        <Link
          href={job.applicationUrl}
          className="inline-block px-6 py-3 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition-colors"
        >
          Apply
        </Link>
      </section>
    </div>
  );
}
